# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            b.wetz
tagline:          'Brandon Wetzel'
description:	  'brandon wetzel'
url:              http://mauzy.ga
baseurl:          /

author:
  name:           'Brandon Wetzel'
  url:            https://github.com/mauzybroadway

paginate:         5
paginate_path:	  /blog/page:num

# Custom vars
version:          2.1.0

github:		  https://github.com/mauzybroadway/
#  main:           https://github.com/mauzybroadway/
#  synth:	  https://github.com/mauzybroadway/mycrosinth
